---
- hosts: localhost
  tasks:
    - name: build website
      command: flutter build web --release --base-href=/app/
      args:
        chdir: ../
- hosts: main
  user: admin
  tasks:
    - name: sync web app files
      synchronize:
        src: "../build/web/"
        dest: "~/nginx/var/www/app/"
        mode: push
        recursive: yes